# Generated by Django 6.0.2 on 2026-03-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='order',
        ),
        migrations.AddField(
            model_name='ministry',
            name='leader_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ministries/leaders/'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='icon_class',
            field=models.CharField(default='fa-heart', help_text='Clase de FontAwesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar (opcional)'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horario (opcional)'),
        ),
    ]
