# Generated by Django 6.0.2 on 2026-03-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-sent_at"]},
        ),
    ]
