# Generated by Django 6.0.2 on 2026-03-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Destacar en inicio"),
        ),
    ]
